name: TumAuth
main: tum.auth.TumAuth
version: 1.0

commands:
  gommemode:
    description: Fucking Gommemode
    usage: /<command>
    permission: tumauth.gommemode
  update_auth_config:
    description: Reloads plugin config
    usage: /<command>
    permission: tumauth.reloadconfig
  tum-id:
    description: Sets your TUM-ID
    usage: /<command> <tum id>
    permission: tumauth.authenticate